#!C:/Program\ Files/Git/usr/bin/sh.exe
#
# This will run CFLint and report an errors.
# If warnings are fount - the commit will be halted.
# Info issues will be committed!

java -jar D:\\tacfug\\CFLint-1.3.0-all.jar --file test.cfc -text -textfile results.txt

if grep -i warnings results.txt
	then
		echo "CFLint errors found - halting commit!"
		rm -f results.txt
		exit 1;
	else
		echo "No CFLint errors found - proceeding with commit..."
		rm -f results.txt
		exit 0
fi

